In [ ]:
from google.colab import files
uploaded = files.upload()
for fn in uploaded.keys():
  print(f'User uploaded file "{fn}" with length {len(uploaded[fn])} bytes')

Saving eye_score.csv to eye_score.csv
User uploaded file "eye_score.csv" with length 1791968 bytes

In [ ]:
import pandas as pd
import io
df = pd.read_csv("eye_score.csv")

In [ ]:
df.head()

,Unnamed: 0,id,exercise_hours,mental_health_score,screen_time_hours,screen_brightness_avg,age,height_cm,outdoor_light_exposure_hours,night_mode_usage,screen_distance_cm,glasses_number,eye_health_score
0,0,1,3.441116,50.112741,4.387540,68.531464,56,172.766324,1.821210,79.091607,33.408167,3,45.492089
1,1,2,7.494288,66.181801,9.596943,54.460165,19,180.683155,0.455726,90.535187,54.127821,0,74.610049
2,2,3,2.733887,69.674360,12.272036,74.334277,76,185.319068,0.301454,11.488773,50.769790,0,52.643897
3,3,4,8.122516,70.996764,8.820065,56.450697,65,166.770667,1.226576,83.373275,51.267787,2,65.963707
4,4,5,1.769984,50.017834,10.962927,87.181496,25,165.203603,0.521827,89.394952,54.595573,0,66.109601

In [ ]:
df.shape

(10000, 13)

In [ ]:
df.columns

Index(['Unnamed: 0', 'id', 'exercise_hours', 'mental_health_score',
       'screen_time_hours', 'screen_brightness_avg', 'age', 'height_cm',
       'outdoor_light_exposure_hours', 'night_mode_usage',
       'screen_distance_cm', 'glasses_number', 'eye_health_score'],
      dtype='object')

In [ ]:
df.dtypes

Unnamed: 0                        int64
id                                int64
exercise_hours                  float64
mental_health_score             float64
screen_time_hours               float64
screen_brightness_avg           float64
age                               int64
height_cm                       float64
outdoor_light_exposure_hours    float64
night_mode_usage                float64
screen_distance_cm              float64
glasses_number                    int64
eye_health_score                float64
dtype: object

In [ ]:
df.isna().sum()

Unnamed: 0                      0
id                              0
exercise_hours                  0
mental_health_score             0
screen_time_hours               0
screen_brightness_avg           0
age                             0
height_cm                       0
outdoor_light_exposure_hours    0
night_mode_usage                0
screen_distance_cm              0
glasses_number                  0
eye_health_score                0
dtype: int64

In [ ]:
value = 0
filtered_df = df[df["age"] > value]
filtered_df

,Unnamed: 0,id,exercise_hours,mental_health_score,screen_time_hours,screen_brightness_avg,age,height_cm,outdoor_light_exposure_hours,night_mode_usage,screen_distance_cm,glasses_number,eye_health_score
0,0,1,3.441116,50.112741,4.387540,68.531464,56,172.766324,1.821210,79.091607,33.408167,3,45.492089
1,1,2,7.494288,66.181801,9.596943,54.460165,19,180.683155,0.455726,90.535187,54.127821,0,74.610049
2,2,3,2.733887,69.674360,12.272036,74.334277,76,185.319068,0.301454,11.488773,50.769790,0,52.643897
3,3,4,8.122516,70.996764,8.820065,56.450697,65,166.770667,1.226576,83.373275,51.267787,2,65.963707
4,4,5,1.769984,50.017834,10.962927,87.181496,25,165.203603,0.521827,89.394952,54.595573,0,66.109601
...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,9995,9996,1.338703,56.768322,0.854225,58.164274,11,143.559342,0.407882,74.331800,63.556015,0,75.669820
9996,9996,9997,0.525389,85.442520,6.889407,86.873212,41,179.409140,4.117332,29.781284,37.564927,3,51.730746
9997,9997,9998,3.190260,87.468755,7.796498,63.268931,57,180.484107,2.321639,76.794358,52.927722,2,61.402673
9998,9998,9999,7.222904,74.331541,3.556995,84.804226,22,159.375346,2.794297,76.676388,43.333935,0,74.063825
9999,9999,10000,1.737612,94.941119,1.816635,67.509092,42,160.656867,0.812032,78.536924,54.429241,0,77.180721